{
    "name": "DReyes Clover Sync",
    "summary": "Sincronización bidireccional entre Odoo y Clover",
    "version": "18.0.1.0.0",
    "author": "DReyes",
    "website": "https://dreyeslatinmarket.com",
    "category": "Sales/Point of Sale",
    "license": "LGPL-3",
    "depends": [
        "account",
        "mail",
        "point_of_sale",
        "product",
        "stock",
        "website",
    ],
    "external_dependencies": {"python": ["cryptography", "requests"]},
    "data": [
        "security/clover_security.xml",
        "security/ir.model.access.csv",
        "data/clover_cron.xml",
        "views/clover_sync_views.xml",
        "views/clover_connector_views.xml",
        "views/clover_product_views.xml",
        "views/clover_order_views.xml",
        "views/clover_menus.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
}
