#version: '3.8'
services:
  web:
    container_name: ${ODOO_CONTAINER_NAME}
    image: ${ODOO_IMAGE}
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
    environment:
      HOST: ${DB_HOST}
      USER: ${DB_USER}
      PASSWORD: ${DB_PASSWORD}      
    command: odoo -d dreyes -u dom_portal   
  db:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_IMAGE}
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - odoo-db-data:${PGDATA}

volumes:
  odoo-web-data:
  odoo-db-data:
